-- MY_PROJECT_ANALYTICS/INSIGHT_REPORT/views/customer_vw.sql
CREATE OR REPLACE VIEW MY_PROJECT_ANALYTICS_{{ env }}_DB.INSIGHT_REPORT.CUSTOMER_VW
AS
SELECT
    CUST_ID,
    CUST_NAME
FROM MY_PROJECT_PREP_{{ env }}_DB.BASE_MODEL.CUSTOMER;