"""Discovery, ordering, and validation for the per-env-folder model.

Repo layout (per-env top folders, REAL env names, no tokens):
    MY_PROJECT_PREP_DEV/BASE_MODEL/tables/customer.sql   -> _DEV_DB names
    MY_PROJECT_PREP_TST/BASE_MODEL/tables/customer.sql   -> _TST_DB names
    MY_PROJECT_PREP_PRD/BASE_MODEL/tables/customer.sql   -> _PRD_DB names

DEV files are authored (via capture). TST and PRD folders are GENERATED by
convert_env.py and must never be hand-edited.
"""

import pathlib
import re

REPO_ROOT = pathlib.Path(__file__).parent.parent

# Logical object trees, WITHOUT the env suffix.
OBJECT_BASES = ["MY_PROJECT_PREP", "MY_PROJECT_ANALYTICS"]

CREATE_RE = re.compile(
    r"CREATE\s+(?:OR\s+(?:REPLACE|ALTER)\s+)?(?:TABLE|VIEW)\s+"
    r"(?:IF\s+NOT\s+EXISTS\s+)?([A-Z0-9_.]+)",
    re.IGNORECASE,
)
REPLACE_TABLE = re.compile(r"CREATE\s+OR\s+REPLACE\s+TABLE", re.IGNORECASE)


def env_top(base, env):
    """MY_PROJECT_PREP + tst -> MY_PROJECT_PREP_TST"""
    return f"{base}_{env.upper()}"


def build_manifest(cfg, target=None):
    """Files for THIS env, in deploy order (tables before views)."""
    env = cfg["env"]
    files = []
    for obj_type in cfg["deploy_order"]:
        for base in OBJECT_BASES:
            root = REPO_ROOT / env_top(base, env)
            if root.exists():
                files.extend(sorted(root.rglob(f"{obj_type}/*.sql")))
    if target:
        files = [f for f in files if target in str(f.relative_to(REPO_ROOT))]
    return files


def validate_no_replace_table(path, raw_text):
    if REPLACE_TABLE.search(raw_text):
        raise ValueError(
            f"{path.relative_to(REPO_ROOT)}: CREATE OR REPLACE TABLE drops data. "
            f"Use CREATE OR ALTER TABLE instead."
        )


def extract_object_name(sql):
    m = CREATE_RE.search(sql)
    if not m:
        raise ValueError("No CREATE TABLE/VIEW statement found")
    return m.group(1).upper()


def object_type(path):
    return path.parent.name


def derive_expected_name(path, env):
    """Path implies the fully qualified name, WITH real env in the DB.

    MY_PROJECT_PREP_TST/BASE_MODEL/tables/customer.sql + TST
    -> MY_PROJECT_PREP_TST_DB.BASE_MODEL.CUSTOMER
    """
    parts = path.relative_to(REPO_ROOT).parts
    if len(parts) != 4:
        raise ValueError(
            f"{path.relative_to(REPO_ROOT)}: expected TOP_ENV/SCHEMA/TYPE/name.sql"
        )
    top_env, schema, _obj_type, filename = parts
    # top_env is like MY_PROJECT_PREP_TST; strip the _ENV suffix to get base
    suffix = f"_{env.upper()}"
    if not top_env.endswith(suffix):
        raise ValueError(f"{top_env}: folder does not end in {suffix} for env {env}")
    base = top_env[: -len(suffix)]
    name = pathlib.Path(filename).stem.upper()
    return f"{base}_{env.upper()}_DB.{schema}.{name}"


def validate_file(path, sql, env):
    """Rendered/real DDL must create exactly what the path implies."""
    expected = derive_expected_name(path, env)
    actual = extract_object_name(sql)
    if actual != expected:
        raise ValueError(
            f"{path.relative_to(REPO_ROOT)}: DDL creates {actual} "
            f"but path implies {expected}"
        )


def derive_path_from_name(object_name, env, obj_type):
    """Inverse: name -> per-env path. Used by capture (dev only).

    MY_PROJECT_PREP_DEV_DB.BASE_MODEL.CUSTOMER + dev + tables
    -> MY_PROJECT_PREP_DEV/BASE_MODEL/tables/customer.sql
    """
    parts = object_name.upper().split(".")
    if len(parts) != 3:
        raise ValueError(f"{object_name}: expected DB.SCHEMA.OBJECT")
    db, schema, name = parts
    suffix = f"_{env.upper()}_DB"
    if not db.endswith(suffix):
        raise ValueError(f"{db}: expected database ending in {suffix}")
    base = db[: -len(suffix)]
    top_env = f"{base}_{env.upper()}"
    return REPO_ROOT / top_env / schema / obj_type / f"{name.lower()}.sql"
