"""Discovery, ordering, and validation for the per-env-folder model.

Naming convention (ONE place — change it here and everything follows):

    database : MY_PROJECT_<ENV>_<LAYER>_DB
    folder   : MY_PROJECT_<ENV>_<LAYER>_DB/<SCHEMA>/<type>/<name>.sql

The folder name IS the database name. Nothing to translate:

    MY_PROJECT_DEV_PREP_DB/BASE_MODEL/tables/customer.sql
        -> MY_PROJECT_DEV_PREP_DB.BASE_MODEL.CUSTOMER

DEV folders are authored (via capture). TST and PRD folders are GENERATED by
convert_env.py and must never be hand-edited.

MD (MY_PROJECT_<ENV>_MD_DB) holds DEPLOYMENT_HISTORY only. It has no repo
folder because the pipeline does not deploy objects into it.
"""

import pathlib
import re

REPO_ROOT = pathlib.Path(__file__).parent.parent

PROJECT = "MY_PROJECT"
LAYERS = ["PREP", "ANALYTICS"]  # layers that hold deployable objects

CREATE_RE = re.compile(
    r"CREATE\s+(?:OR\s+(?:REPLACE|ALTER)\s+)?(?:TABLE|VIEW)\s+"
    r"(?:IF\s+NOT\s+EXISTS\s+)?([A-Z0-9_.]+)",
    re.IGNORECASE,
)
REPLACE_TABLE = re.compile(r"CREATE\s+OR\s+REPLACE\s+TABLE", re.IGNORECASE)


def db_name(layer, env):
    """MY_PROJECT_DEV_PREP_DB — also the folder name."""
    return f"{PROJECT}_{env.upper()}_{layer.upper()}_DB"


def env_folders(env):
    """All repo folders for an env, in LAYERS order."""
    return [db_name(layer, env) for layer in LAYERS]


def build_manifest(cfg, target=None):
    """Files for THIS env, in deploy order (tables before views)."""
    env = cfg["env"]
    files = []
    for obj_type in cfg["deploy_order"]:
        for folder in env_folders(env):
            root = REPO_ROOT / folder
            if root.exists():
                files.extend(sorted(root.rglob(f"{obj_type}/*.sql")))
    if target:
        files = [f for f in files if target in str(f.relative_to(REPO_ROOT))]
    return files


def validate_no_replace_table(path, raw_text):
    if REPLACE_TABLE.search(raw_text):
        raise ValueError(
            f"{path.relative_to(REPO_ROOT)}: CREATE OR REPLACE TABLE drops data. "
            f"Use CREATE OR ALTER TABLE instead."
        )


def extract_object_name(sql):
    m = CREATE_RE.search(sql)
    if not m:
        raise ValueError("No CREATE TABLE/VIEW statement found")
    return m.group(1).upper()


def object_type(path):
    return path.parent.name


def derive_expected_name(path, env):
    """The top folder IS the database, so the name falls straight out.

    MY_PROJECT_DEV_PREP_DB/BASE_MODEL/tables/customer.sql
    -> MY_PROJECT_DEV_PREP_DB.BASE_MODEL.CUSTOMER
    """
    parts = path.relative_to(REPO_ROOT).parts
    if len(parts) != 4:
        raise ValueError(
            f"{path.relative_to(REPO_ROOT)}: expected "
            f"{PROJECT}_<ENV>_<LAYER>_DB/SCHEMA/TYPE/name.sql"
        )
    db, schema, _obj_type, filename = parts
    prefix = f"{PROJECT}_{env.upper()}_"
    if not db.startswith(prefix) or not db.endswith("_DB"):
        raise ValueError(
            f"{db}: folder must look like {prefix}<LAYER>_DB for env {env}"
        )
    name = pathlib.Path(filename).stem.upper()
    return f"{db}.{schema}.{name}"


def validate_file(path, sql, env):
    """DDL must create exactly what the path implies."""
    expected = derive_expected_name(path, env)
    actual = extract_object_name(sql)
    if actual != expected:
        raise ValueError(
            f"{path.relative_to(REPO_ROOT)}: DDL creates {actual} "
            f"but path implies {expected}"
        )


def derive_path_from_name(object_name, env, obj_type):
    """Inverse: name -> path. The database part IS the folder.

    MY_PROJECT_DEV_PREP_DB.BASE_MODEL.CUSTOMER + dev + tables
    -> MY_PROJECT_DEV_PREP_DB/BASE_MODEL/tables/customer.sql
    """
    parts = object_name.upper().split(".")
    if len(parts) != 3:
        raise ValueError(f"{object_name}: expected DB.SCHEMA.OBJECT")
    db, schema, name = parts
    prefix = f"{PROJECT}_{env.upper()}_"
    if not db.startswith(prefix) or not db.endswith("_DB"):
        raise ValueError(f"{db}: expected database like {prefix}<LAYER>_DB")
    return REPO_ROOT / db / schema / obj_type / f"{name.lower()}.sql"
