-- MY_PROJECT_PREP/BASE_MODEL/tables/customer.sql
CREATE TABLE OR REPLACE MY_PROJECT_PREP_{{ env }}_DB.BASE_MODEL.CUSTOMER (
    CUST_ID    NUMBER,
    CUST_NAME  VARCHAR(200),
    CUST_EMAIL VARCHAR(200)
);