-- MY_PROJECT_PREP/BASE_MODEL/tables/payments.sql
CREATE OR ALTER TABLE MY_PROJECT_PREP_{{ env }}_DB.BASE_MODEL.PAYMENTS (
	PAYMENT_ID NUMBER(38,0),
	ORDER_ID NUMBER(38,0),
	PAYMENT_DATE DATE,
	AMOUNT NUMBER(10,2),
	METHOD VARCHAR(50)
);
