-- MY_PROJECT_PREP/BASE_MODEL/tables/product.sql
CREATE OR ALTER TABLE MY_PROJECT_PREP_{{ env }}_DB.BASE_MODEL.PRODUCT (
	PRD_ID NUMBER(38,0),
	PRD_NAME VARCHAR(200),
	PRD_CATEGORY VARCHAR(200),
	PRD_DESC VARCHAR(500),
	TIME TIMESTAMP_NTZ(9)
);
