-- MY_PROJECT_PREP/BASE_MODEL/tables/customer.sql
CREATE TABLE IF NOT EXISTS MY_PROJECT_PREP_{{ env }}_DB.BASE_MODEL.PRODUCT (
    PRD_ID    NUMBER,
    PRD_NAME  VARCHAR(200),
    PRD_CATEGORY VARCHAR(200)
);
